version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.3.0
      command: /sbin/init
    - image: circleci/postgres:9.6.8-alpine-postgis-ram
    environment:
      NODE_ENV: circleci
    steps:
    - checkout
    - setup_remote_docker
    - restore_cache: # special step to restore the dependency cache
        key: cache-{{ checksum "package.json" }}
    - run: sudo apt -y update
    - run: sudo apt -y install postgresql-client
    # Cypress dependencies
    # See: https://github.com/cypress-io/cypress-docker-images/blob/master/base/ubuntu16/Dockerfile
    - run: sudo apt -y install libgtk2.0-0
    - run: sudo apt -y install libnotify-dev
    - run: sudo apt -y install libgconf-2-4 libnss3 libxss1
    - run: sudo apt -y install libasound2 xvfb
    - run: npm ci
    - run: ./scripts/setup_circleci.sh
    - save_cache: # special step to save the dependency cache
        key: cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
          - ../.cache
          - ../cache
    - run: npm run test
    - store_test_results:
        path: /tmp/circleci-test-results
